dist: bionic
sudo: required
language: go
go:
  - 1.11
  - 1.12
go_import_path: v2.staffjoy.com
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-11-jdk
      - bazel
      - wget
      - pkg-config
install:
  - mkdir $GOPATH/bin
  - go get github.com/PuerkitoBio/goquery
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get github.com/bazelbuild/buildifier/buildifier
  - make build
script:
  - make test
