dist: bionic
sudo: required
language: go
env:
  - GO111MODULE=on
go:
  - 1.12
node_js:
  - 10
go_import_path: v2.staffjoy.com
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openjdk-11-jdk
      - bazel
      - wget
      - pkg-config
install:
  - curl https://glide.sh/get | sh
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/goimports
  - go get github.com/bazelbuild/buildifier/buildifier
  - make build
script:
  - make test
