apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: botserver-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: botserver
    spec:
      containers:
      - name: botserver-container
        image: localhost:5000/botserver:VERSION
        ports:
        - containerPort: 80
        - containerPort: 1000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
