apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: companyserver-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: companyserver
    spec:
      containers:
      - name: companyserver-container
        image: localhost:5000/companyserver:VERSION
        ports:
        - containerPort: 80
        - containerPort: 1000
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: MYSQL_CONFIG
          value: "root:SHIBBOLETH@tcp(app-mysql-service:3306)/company"
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SIGNING_SECRET
          value: QqvNDpRMnDvuDZL2xCtVwdNPEX2jYhKyzuX3VzQEdfmruNNysxVRGdWXuin6jhdQ
        - name: SUITE_API_KEY
          value: SeCrEt