apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faraday-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: faraday
    spec:
      containers:
      - name: faraday-container
        image: localhost:5000/faraday:VERSION
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        env:
        - name: DEPLOY
          value: VERSION
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SIGNING_SECRET
          value: QqvNDpRMnDvuDZL2xCtVwdNPEX2jYhKyzuX3VzQEdfmruNNysxVRGdWXuin6jhdQ
